### ISSUE TITLE
Pdfs manquants

### ISSUE THREAD

**Issue by mariebarras** [gabays/32M7128#1]
Hello Simon, 

Je viens de réaliser que je n'avais pas téléchargé les pdfs de l'année passée pour le cours, et il manque les pdfs des cours 6, 7 et 10... Est-ce qu'il y a un moyen que je les génère moi directement ou est-ce que c'est toi qui as la main là dessus ? 

Mille mercis ! 

Marie

**Comment by gabays** [comment]
https://marp.app/
